using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
var builder=WebApplication.CreateBuilder(args);builder.WebHost.UseUrls("http://0.0.0.0:5090");var app=builder.Build();
var dir=Path.Combine(AppContext.BaseDirectory,"data");Directory.CreateDirectory(dir);
string B=Path.Combine(dir,"bookings.json"),U=Path.Combine(dir,"users.json"),D=Path.Combine(dir,"doctors.json"),E=Path.Combine(dir,"exams.json"),A=Path.Combine(dir,"activity.json"),C=Path.Combine(dir,"capacity.json");
Init(B,"[]");Init(D,JsonSerializer.Serialize(new[]{"Dr. Ahmed","Dr. Mohamed"}));Init(E,JsonSerializer.Serialize(new[]{"Abdominal Ultrasound","Pelvic Ultrasound","Doppler","Echocardiography"}));Init(A,"[]");Init(C,"[]");
if(!File.Exists(U)){var initialUsers=new List<User>{new User{username="admin",password=Hash("admin123"),name="Administrator",role="Super Admin",permissions=new[]{"bookings.view","bookings.add","bookings.edit","bookings.delete","users.manage","masters.manage","backup","reports"}}};File.WriteAllText(U,JsonSerializer.Serialize(initialUsers));}
app.UseDefaultFiles();app.UseStaticFiles();
app.MapPost("/api/login",async(HttpRequest r)=>{var x=await JsonSerializer.DeserializeAsync<Login>(r.Body);var us=Read<User>(U);var u=us.FirstOrDefault(z=>x!=null&&z.username.Equals(x.username,StringComparison.OrdinalIgnoreCase)&&z.password==Hash(x.password));if(u==null)return Results.Unauthorized();return Results.Ok(new{u.username,u.name,u.role,u.permissions});});
app.MapGet("/api/bookings",()=>Json(Read<Booking>(B)));
app.MapPost("/api/bookings",async(HttpRequest r)=>{var x=await JsonSerializer.DeserializeAsync<Booking>(r.Body);if(x==null)return Results.BadRequest();var a=Read<Booking>(B);var g=CapacityGate(x,a,null);if(g.full&&!IsAdminActor(x.modifiedBy,x.bookedBy))return Results.Conflict(new{error="capacity_full",used=g.used,max=g.max});if(g.full)Log(x.modifiedBy,"CAPACITY OVERRIDE",x.doctor+" / "+x.shift+" / "+x.bookingDate.ToString("yyyy-MM-dd")+" ("+g.used+"/"+g.max+")");x.id=Guid.NewGuid().ToString("N")[..8].ToUpper();x.createdAt=x.updatedAt=DateTime.Now;a.Add(x);Write(B,a);Log(x.bookedBy,"ADD BOOKING",x.id+" - "+x.patientName);return Results.Ok(x);});
app.MapPut("/api/bookings/{id}",async(string id,HttpRequest r)=>{var x=await JsonSerializer.DeserializeAsync<Booking>(r.Body);var a=Read<Booking>(B);var i=a.FindIndex(z=>z.id==id);if(x==null||i<0)return Results.NotFound();var g=CapacityGate(x,a,id);if(g.full&&!IsAdminActor(x.modifiedBy,x.bookedBy))return Results.Conflict(new{error="capacity_full",used=g.used,max=g.max});if(g.full)Log(x.modifiedBy,"CAPACITY OVERRIDE",x.doctor+" / "+x.shift+" / "+x.bookingDate.ToString("yyyy-MM-dd")+" ("+g.used+"/"+g.max+")");x.id=id;x.createdAt=a[i].createdAt;x.updatedAt=DateTime.Now;a[i]=x;Write(B,a);Log(x.modifiedBy,"EDIT BOOKING",id+" - "+x.patientName);return Results.Ok(x);});
app.MapPost("/api/bookings/{id}/cancel",(string id,string user)=>{var a=Read<Booking>(B);var x=a.FirstOrDefault(z=>z.id==id);if(x==null)return Results.NotFound();x.status="Cancelled";x.modifiedBy=user;x.updatedAt=DateTime.Now;Write(B,a);Log(user,"CANCEL BOOKING",id+" - "+x.patientName);return Results.Ok(x);});
app.MapGet("/api/users",()=>Json(Read<User>(U).Select(x=>new{x.username,x.name,x.role,x.permissions})));
app.MapPost("/api/users",async(HttpRequest r)=>{var x=await JsonSerializer.DeserializeAsync<UserInput>(r.Body);if(x==null||string.IsNullOrWhiteSpace(x.username)||string.IsNullOrWhiteSpace(x.password))return Results.BadRequest();var a=Read<User>(U);if(a.Any(z=>z.username.Equals(x.username,StringComparison.OrdinalIgnoreCase)))return Results.Conflict();a.Add(new User{username=x.username,name=x.name,password=Hash(x.password),role=x.role,permissions=x.permissions??[]});Write(U,a);Log(x.actor,"ADD USER",x.username);return Results.Ok();});
app.MapPut("/api/users/{name}",async(string name,HttpRequest r)=>{var x=await JsonSerializer.DeserializeAsync<UserUpdate>(r.Body);if(x==null)return Results.BadRequest();var a=Read<User>(U);var u=a.FirstOrDefault(z=>z.username==name);if(u==null)return Results.NotFound();u.name=x.name;u.role=x.role;u.permissions=x.permissions??[];if(!string.IsNullOrWhiteSpace(x.password))u.password=Hash(x.password);Write(U,a);Log(x.actor,"UPDATE USER",name);return Results.Ok();});
app.MapPost("/api/change-password",async(HttpRequest r)=>{var x=await JsonSerializer.DeserializeAsync<PasswordChange>(r.Body);if(x==null)return Results.BadRequest();var a=Read<User>(U);var u=a.FirstOrDefault(z=>z.username==x.username&&z.password==Hash(x.oldPassword));if(u==null)return Results.Unauthorized();u.password=Hash(x.newPassword);Write(U,a);Log(u.name,"CHANGE PASSWORD",u.username);return Results.Ok();});
app.MapDelete("/api/users/{name}",(string name,string actor)=>{if(name=="admin")return Results.BadRequest();var a=Read<User>(U);a.RemoveAll(x=>x.username==name);Write(U,a);Log(actor,"DELETE USER",name);return Results.Ok();});
app.MapGet("/api/doctors",()=>Json(Read<string>(D)));app.MapPost("/api/doctors",async(HttpRequest r)=>{var x=await JsonSerializer.DeserializeAsync<Master>(r.Body);if(x==null||string.IsNullOrWhiteSpace(x.value))return Results.BadRequest();var a=Read<string>(D);if(!a.Contains(x.value,StringComparer.OrdinalIgnoreCase))a.Add(x.value.Trim());Write(D,a);Log(x.actor,"ADD DOCTOR",x.value);return Results.Ok();});app.MapDelete("/api/doctors",(string value,string actor)=>{var a=Read<string>(D);a.RemoveAll(x=>x.Equals(value,StringComparison.OrdinalIgnoreCase));Write(D,a);Log(actor,"DELETE DOCTOR",value);return Results.Ok();});
app.MapGet("/api/exams",()=>Json(Read<string>(E)));app.MapPost("/api/exams",async(HttpRequest r)=>{var x=await JsonSerializer.DeserializeAsync<Master>(r.Body);if(x==null||string.IsNullOrWhiteSpace(x.value))return Results.BadRequest();var a=Read<string>(E);if(!a.Contains(x.value,StringComparer.OrdinalIgnoreCase))a.Add(x.value.Trim());Write(E,a);Log(x.actor,"ADD EXAM",x.value);return Results.Ok();});app.MapDelete("/api/exams",(string value,string actor)=>{var a=Read<string>(E);a.RemoveAll(x=>x.Equals(value,StringComparison.OrdinalIgnoreCase));Write(E,a);Log(actor,"DELETE EXAM",value);return Results.Ok();});
app.MapGet("/api/capacity",()=>Json(Read<Capacity>(C)));app.MapPost("/api/capacity",async(HttpRequest r)=>{var x=await JsonSerializer.DeserializeAsync<Capacity>(r.Body);if(x==null||string.IsNullOrWhiteSpace(x.doctor)||x.maxBookings<1)return Results.BadRequest();var a=Read<Capacity>(C);var old=a.FirstOrDefault(z=>z.doctor==x.doctor&&z.shift==x.shift);if(old==null)a.Add(x);else old.maxBookings=x.maxBookings;Write(C,a);Log(x.actor,"SET CAPACITY",x.doctor+" / "+x.shift+" = "+x.maxBookings);return Results.Ok();});
app.MapGet("/api/activity",()=>Json(Read<Activity>(A).OrderByDescending(x=>x.time).Take(500)));app.MapGet("/api/health",()=>Results.Ok(new{status="ok",server=Environment.MachineName,time=DateTime.Now,bookings=Read<Booking>(B).Count,users=Read<User>(U).Count,dataPath=dir}));
app.MapGet("/api/backup",()=>{var stamp=CreateBackup();Log("SYSTEM","BACKUP",stamp);return Results.Ok(new{folder=stamp});});app.MapGet("/api/backups",()=>{var root=Path.Combine(dir,"backups");Directory.CreateDirectory(root);return Results.Json(Directory.GetDirectories(root).Select(Path.GetFileName).OrderByDescending(x=>x));});app.MapPost("/api/restore/{stamp}",(string stamp,string user)=>{var root=Path.Combine(dir,"backups");var bd=Path.Combine(root,Path.GetFileName(stamp));if(!Directory.Exists(bd))return Results.NotFound();CreateBackup();foreach(var target in new[]{B,U,D,E,A,C}){var src=Path.Combine(bd,Path.GetFileName(target));if(File.Exists(src))File.Copy(src,target,true);}Log(user,"RESTORE BACKUP",stamp);return Results.Ok();});
var autoStamp=DateTime.Now.ToString("yyyyMMdd");var marker=Path.Combine(dir,"backup_"+autoStamp+".done");if(!File.Exists(marker)){CreateBackup();File.WriteAllText(marker,DateTime.Now.ToString("O"));}\napp.MapArabicV2(dir);\napp.Run();
void Init(string p,string v){if(!File.Exists(p))File.WriteAllText(p,v);}List<T> Read<T>(string p)=>JsonSerializer.Deserialize<List<T>>(File.ReadAllText(p))??[];void Write<T>(string p,IEnumerable<T> x)=>File.WriteAllText(p,JsonSerializer.Serialize(x,new JsonSerializerOptions{WriteIndented=true}));IResult Json(object x)=>Results.Json(x);void Log(string user,string action,string detail){var a=Read<Activity>(A);a.Add(new Activity{time=DateTime.Now,user=user,action=action,detail=detail});Write(A,a);}
(bool full,int used,int max) CapacityGate(Booking x,List<Booking> a,string? ignore){var rule=Read<Capacity>(C).FirstOrDefault(z=>z.doctor==x.doctor&&z.shift==x.shift);if(rule==null)return(false,0,0);var used=a.Count(z=>z.id!=ignore&&z.status!="Cancelled"&&z.doctor==x.doctor&&z.shift==x.shift&&z.bookingDate.Date==x.bookingDate.Date);return(used>=rule.maxBookings,used,rule.maxBookings);}bool IsAdminActor(params string[] names){var us=Read<User>(U);return names.Where(n=>!string.IsNullOrWhiteSpace(n)).Any(n=>us.Any(u=>(u.name.Equals(n,StringComparison.OrdinalIgnoreCase)||u.username.Equals(n,StringComparison.OrdinalIgnoreCase))&&(u.role=="Admin"||u.role=="Super Admin")));}
string CreateBackup(){var stamp=DateTime.Now.ToString("yyyyMMdd_HHmmss");var bd=Path.Combine(dir,"backups",stamp);Directory.CreateDirectory(bd);foreach(var f in new[]{B,U,D,E,A,C})if(File.Exists(f))File.Copy(f,Path.Combine(bd,Path.GetFileName(f)),true);return stamp;}static string Hash(string s)=>Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(s)));
record Login(string username,string password);record Master(string value,string actor);record PasswordChange(string username,string oldPassword,string newPassword);class User{public string username{get;set;}="";public string password{get;set;}="";public string name{get;set;}="";public string role{get;set;}="User";public string[] permissions{get;set;}=[];}class UserInput:User{public string actor{get;set;}="";}class UserUpdate{public string name{get;set;}="";public string role{get;set;}="User";public string password{get;set;}="";public string[] permissions{get;set;}=[];public string actor{get;set;}="";}class Activity{public DateTime time{get;set;}public string user{get;set;}="";public string action{get;set;}="";public string detail{get;set;}="";}class Capacity{public string doctor{get;set;}="";public string shift{get;set;}="Morning";public int maxBookings{get;set;}=20;public string actor{get;set;}="";}class Booking{public string id{get;set;}="";public string patientName{get;set;}="";public string patientId{get;set;}="";public string phone{get;set;}="";public string exam{get;set;}="";public string doctor{get;set;}="";public DateTime bookingDate{get;set;}public string shift{get;set;}="Morning";public string status{get;set;}="New";public bool papersReceived{get;set;}public string notes{get;set;}="";public string bookedBy{get;set;}="";public string modifiedBy{get;set;}="";public DateTime createdAt{get;set;}public DateTime updatedAt{get;set;}}